config/routes.rb
Rails.application.routes.draw do

  #ルート++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  root 'contests#index'
  #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  #コンテスト+++++++++++++++++++++++++++++++++++++++++++++++++++++
  #index無限スクロール
  get 'contests/more', to: 'contests#index_ajax', as: 'contests_index_ajax'
  resources :contests, except: [:index] do
    #コンテストに紐付けられた写真
    resources :photos
    #コンテストに紐付けられた投票
    resources :votes, only: [:index, :new, :create, :destroy]
  end
  #+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  #ユーザ++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  devise_for(
    :users,
    path: '',
    module: 'users',
    path_names: { registration: 'users' }
  )
  devise_scope :user do
    get 'users/:id', to: 'users/registrations#show', as: 'user'
  end
  #+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  #ユーザに紐付けられた写真++++++++++++++++++++++++++++++++++++++++
  resources :users, only: [] do
    resources :photos, only: [:show, :edit, :update, :destroy]
  end
  #+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  #限定公開URL制御+++++++++++++++++++++++++++++++++++++++++++++++++
  patch 'url', to: 'urls#update'
  #+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  #管理画面+++++++++++++++++++++++++++++++++++++++++++++++++++++++
  get 'contests/:contest_id/admin', to: 'admin#index', as: 'admin'
  delete 'contests/:contest_id/admin/photo/:id', to: 'admin#photo_delete', as: 'admin_photo'

  #静的ページ+++++++++++++++++++++++++++++++++++++++++++++++++++++
  get 'aboutus', to: 'static_pages#aboutus'
  #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_action :check_logged_in, except: [:index, :show, :index_ajax]
  before_action :check_correct_user, only: [:edit, :update, :destory]

  def index
    @contests = Contest.public_all.order('contests.created_at DESC').includes(:user).page(params[:page]).per(10)
    @contests_submited = Contest.joins(:photos).where('photos.user_id = ?', current_user.id).order('photos.created_at DESC').includes(:user).page(params[:page]).per(10) if signed_in?
    @submited_photos = Photo.where(user: current_user).order('created_at DESC').limit(5).select('id, name, contest_id') if signed_in?
  end

  def show
    if @contest = Contest.find_by(id: params[:id])
      @user_photos = @contest.photos.where(user: current_user).order('created_at ASC')
      @urls = Url.new().urls_for_view(@contest)
    else
      flash[:danger] = 'コンテストは存在しません'
      redirect_to root_path
    end
  end

  def new
    @contest = Contest.new
    @contest.initialize_for_form
  end

  def create
    @contest ||= Contest.new(contest_params)
    @contest.user_id = current_user.id
    @contest.create_limited_url
    if @contest.save
      flash[:success] = 'コンテストを作成しました'
      redirect_to @contest
    else
      render :new
    end
  end

  def edit
    @contest ||= Contest.find_by(id: params[:id])
  end

  def update
    @contest ||= Contest.find_by(id: params[:id])
    if @contest && @contest.update(contest_params)
      redirect_to contest_path(@contest), success: 'コンテストを変更しました'
    else
      render :edit, danger: 'コンテストの変更に失敗しました'
    end
  end

  def destroy
    @contest ||= Contest.find_by(id: params[:id])
    if @contest && @contest.destroy
      flash[:success] = 'コンテストを削除しました'
      redirect_to root_path
    else
      flash[:danger] = 'コンテストが削除できませんでした'
      redirect_to contest_path(params[:id])
    end
  end

  def index_ajax
    if params[:target] == 'contests'
      @contests = Contest.public_all.order('contests.created_at DESC').includes(:user).page(params[:page]).per(10)
      @target = 'contests'
    elsif params[:target] == 'contests_submited'
      @contests = Contest.joins(:photos).where('photos.user_id = ?', current_user.id).order('photos.created_at DESC').page(params[:page]).per(10) if signed_in?
      @target = 'contests_submited'
    end
  end

  private
    def contest_params
      get = params.require(:contest).permit(
        :name,
        :description,
        :entry_start_at_date, :entry_start_at_time, :entry_end_at_date, :entry_end_at_time,
        :vote_start_at_date, :vote_start_at_time, :vote_end_at_date, :vote_end_at_time,
        :visible_range_entry, :visible_range_vote, :visible_range_show, :visible_range_result,
        :voting_points, :num_of_submit_limit, :num_of_views_in_result,
        :visible_setting_for_user_name
      )

      tmp = {
        entry_start_at: print_datetime_from_string(get[:entry_start_at_date], get[:entry_start_at_time]),
        entry_end_at:   print_datetime_from_string(get[:entry_end_at_date], get[:entry_end_at_time]),
        vote_start_at:  print_datetime_from_string(get[:vote_start_at_date], get[:vote_start_at_time]),
        vote_end_at:    print_datetime_from_string(get[:vote_end_at_date], get[:vote_end_at_time])
      }

      delete_list = %w(entry_start_at_date entry_start_at_time entry_end_at_date entry_end_at_time vote_start_at_date vote_start_at_time vote_end_at_date vote_end_at_time)
      delete_list.each do |value|
        get.delete(value)
      end

      get.merge(tmp)
    end

    def check_correct_user
      @contest ||= Contest.find_by(id: params[:contest_id] || params[:id])
      redirect_back fallback_location: root_path, danger: 'コンテストの取得に失敗しました' and return unless @contest
      @user = @contest.user
      redirect_back fallback_location: root_path, danger: '現在のユーザはこのコンテストの作成者ではありません' and return unless correct_user?(@user)
    end
end

app/helpers/contests_helper.rb
module ContestsHelper
  def content_tag_options_for_contest_badge(contest, current_class)
    if contest.is_after_period_voting?
      if contest.visible_range_result.to_s == '1' && contest.visible_range_show.to_s == '1'
        {tag: 'div', content: t('contests.badge.show_result_invisible'), options: {class: "#{current_class} show_result_invisible inactive"}, value: 4.7 }
      elsif contest.visible_range_result.to_s == '1' && contest.visible_range_show.to_s == '0'
        {tag: 'a', content: t('contests.badge.vote_finish'), options: {href: contest_photos_path(contest), class: "#{current_class} vote_finish"}, value: 4.5 }
      elsif contest.visible_range_result.to_s == '0' && contest.visible_range_show.to_s == '1'
        {tag: 'a', content: t('contests.badge.vote_finish'), options: {href: contest_votes_path(contest), class: "#{current_class} vote_finish"}, value: 4.3 }
      else
        {tag: 'a', content: t('contests.badge.vote_finish'), options: {href: contest_votes_path(contest), class: "#{current_class} vote_finish"}, value: 4 }
      end

    elsif contest.is_in_period_voting?
      if contest.is_already_voted?(current_user)
        {tag: 'div', content: t('contests.badge.already_voted'), options: {class: "#{current_class} already_voted inactive"}, value: 3.7 }
      elsif contest.visible_range_vote.to_s == '1'
        {tag: 'div', content: t('contests.badge.vote_invisible'), options: {class: "#{current_class} vote_invisible inactive"}, value: 3.5 }
      else
        {tag: 'a', content: t('contests.badge.vote_period'), options: {href: new_contest_vote_path(contest), class: "#{current_class} vote_period"}, value: 3 }
      end

    elsif contest.is_after_period_entry?
      if contest.visible_range_vote.to_s == '1'
        {tag: 'div', content: t('contests.badge.vote_invisible'), options: {class: "#{current_class} vote_invisible inactive"}, value: 2.5 }
      else
        {tag: 'div', content: t('contests.badge.vote_preparing'), options: {class: "#{current_class} vote_preparing inactive"}, value: 2 }
      end

    elsif contest.is_in_period_entry?
      if contest.is_already_submitted?(current_user)
        {tag: 'a', content: t('contests.badge.already_entered'), options: {href: edit_contest_photo_path(contest, Photo.find_by(contest: contest, user: current_user)), class: "#{current_class} already_entered"}, value: 1.7 }
      elsif contest.visible_range_entry.to_s == '1'
        {tag: 'div', content: t('contests.badge.entry_invisible'), options: {class: "#{current_class} entry_invisible inactive"}, value: 1.5 }
      else
        {tag: 'a', content: t('contests.badge.entry_period'), options: {href: new_contest_photo_path(contest), class: "#{current_class} entry_period"}, value: 1 }
      end

    else
      if contest.visible_range_entry.to_s == '1'
        {tag: 'div', content: t('contests.badge.entry_invisible'), options: {class: "#{current_class} entry_invisible inactive"}, value: 0.5 }
      else
        {tag: 'div', content: t('contests.badge.entry_preparing'), options: {class: "#{current_class} entry_preparing inactive"}, value: 0 }
      end
    end
  end



  def content_tag_options_for_contest_links(contest, current_class)
    if contest.is_after_period_voting?
      if contest.visible_range_result.to_s == '1' && contest.visible_range_show.to_s == '1'
        [
          {tag: 'div', content: t('contests.links.show_invisible'), options: {class: "#{current_class} show_result_invisible inactive photo_list opposite"}, value: 4.5 },
          {tag: 'div', content: t('contests.links.result_invisible'), options: {class: "#{current_class} show_result_invisible inactive"}, value: 4 }
        ]
      elsif contest.visible_range_result.to_s == '1' && contest.visible_range_show.to_s == '0'
        [
          {tag: 'a', content: t('contests.links.show'), options: {href: contest_photos_path(contest), class: "#{current_class} photo_list opposite"}, value: 4.5 },
          {tag: 'div', content: t('contests.links.result_invisible'), options: {class: "#{current_class} show_result_invisible inactive"}, value: 4 }
        ]
      elsif contest.visible_range_result.to_s == '0' && contest.visible_range_show.to_s == '1'
        [
          {tag: 'div', content: t('contests.links.show_invisible'), options: {class: "#{current_class} show_result_invisible inactive photo_list opposite"}, value: 4.5 },
          {tag: 'a', content: t('contests.links.result'), options: {href: contest_votes_path(contest), class: "#{current_class} vote_finish"}, value: 4 }
        ]
      else
        [
          {tag: 'a', content: t('contests.links.show'), options: {href: contest_photos_path(contest), class: "#{current_class} photo_list opposite"}, value: 4.5 },
          {tag: 'a', content: t('contests.links.result'), options: {href: contest_votes_path(contest), class: "#{current_class} vote_finish"}, value: 4 }
        ]
      end

    elsif contest.is_in_period_voting?
      if contest.is_already_voted?(current_user)
        [
          {tag: 'div', content: t('contests.links.already_voted'), options: {class: "#{current_class} already_voted inactive"}, value: 3 }
        ]
      elsif contest.visible_range_vote.to_s == '1'
        [
          {tag: 'div', content: t('contests.links.vote_invisible'), options: {class: "#{current_class} vote_invisible inactive"}, value: 3 }
        ]
      else
        [
          {tag: 'a', content: t('contests.links.vote'), options: {href: new_contest_vote_path(contest), class: "#{current_class} vote"}, value: 3 }
        ]
      end

    elsif contest.is_after_period_entry?
      if contest.visible_range_vote.to_s == '1'
        [
          {tag: 'div', content: t('contests.links.vote_invisible'), options: {class: "#{current_class} vote_invisible inactive"}, value: 2 }
        ]
      else
        [
          {tag: 'div', content: t('contests.links.vote_prepering'), options: {class: "#{current_class} vote_prepering inactive"}, value: 2 }
        ]
      end

    elsif contest.is_in_period_entry?
      if !contest.is_able_to_submit?(current_user)
        [
          {tag: 'menu', content: t('contests.links.entry_edit'), options: {href: edit_contest_photo_path(contest, Photo.find_by(contest: contest, user: current_user)), class: "#{current_class} entry_edit js-menu opposite", data: {menutarget: 'menu_photos'} }, value: 1.5 },
          {tag: 'div', content: t('contests.links.entry_unable'), options: {class: "#{current_class} entry_unable inactive" }, value: 1 },
        ]
      elsif contest.is_already_submitted?(current_user)
        [
          {tag: 'menu', content: t('contests.links.entry_edit'), options: {href: edit_contest_photo_path(contest, Photo.find_by(contest: contest, user: current_user)), class: "#{current_class} entry_edit js-menu opposite", data: {menutarget: 'menu_photos'} }, value: 1.5 },
          {tag: 'a', content: t('contests.links.entry_continue'), options: {href: new_contest_photo_path(contest), class: "#{current_class} entry_continue" }, value: 1 },
        ]
      elsif contest.visible_range_entry.to_s == '1'
        [
          {tag: 'div', content: t('contests.links.entry_invisible'), options: {class: "#{current_class} entry_invisible inactive"}, value: 1 }
        ]
      else
        [
          {tag: 'a', content: t('contests.links.entry'), options: {href: new_contest_photo_path(contest), class: "#{current_class} entry_period"}, value: 1 }
        ]
      end

    else
      if contest.visible_range_entry.to_s == '1'
        [
          {tag: 'div', content: t('contests.links.entry_invisible'), options: {class: "#{current_class} entry_invisible inactive"}, value: 0 }
        ]
      else contest.visible_range_entry.to_s == '0'
        [
          {tag: 'div', content: t('contests.links.entry_preparing'), options: {class: "#{current_class} entry_preparing inactive"}, value: 0 }
        ]
      end
    end
  end
end

app/views/contests/_badge.html.erb
<% badge_options = content_tag_options_for_contest_badge(contest, 'contest__header-badge') %>
<%= content_tag(badge_options[:tag], badge_options[:content], badge_options[:options]) %>

app/views/contests/_contest.html.erb
<li class="contests__item-container">
  <div class="contests__item__header-container">
    <%= link_to contest.name, contest_path(contest), class: 'contests__item__header-title' %>

    <% unless controller_name == 'registrations' && action_name == 'show' %>
      <%= link_to user_path(contest.user), class: 'contests__item__header-creater-link' do %>
        <p class="contests__item__header-creater-label"><%= t 'contests.item.creater' %></p>
        <%= image_tag contest.user.image.url, class: 'contests__item__header-creater-img' %>
        <p class="contests__item__header-creater-name"><%= contest.user.name %></p>
      <% end %>
    <% end %>

    <% badge_options = content_tag_options_for_contest_badge(contest, 'contests__item__header-badge') %>
    <%= content_tag(badge_options[:tag], badge_options[:content], badge_options[:options]) %>
  </div>

  <%= link_to contest_path(contest), class: 'contests__item__body-container' do %>
    <div class="contests__item__body-main">
      <p class="contests__item__body-main-p <%= 'need' if badge_options[:value] < 2 %>"><%= t 'contests.item.entry_period' %>：<%= print_datetime_with_wday(contest.entry_start_at) %> <i class="fas fa-caret-right"></i> <%= print_datetime_with_wday(contest.entry_end_at) %></p>
      <p class="contests__item__body-main-p <%= 'need' if badge_options[:value] >= 2 %>"><%= t 'contests.item.vote_period' %>：<%= print_datetime_with_wday(contest.vote_start_at) %> <i class="fas fa-caret-right"></i> <%= print_datetime_with_wday(contest.vote_end_at) %></p>
      <p class="contests__item__body-main-p"><%= t 'contests.item.visible_setting_for_user_name' %>：<%= t("contests.select.visible_setting_for_user_name.#{contest.visible_setting_for_user_name}") %></p>
    </div>
    <div class="contests__item__body-sub">
      <div class="contests__item__body-sub-p"><%= contest.excerpt_description(100) %></div>
    </div>
    <div class="arrow_more">more</div>
  <% end %>
</li>

app/views/contests/_contests.html.erb
<% if contests.present? %>
  <%= paginate contests, param_name: "page_contests" %>
  <ul class="contests-container">
      <%= render partial: 'contests/contest', collection: contests %>
  </ul>
  <%= paginate contests, param_name: "page_contests" %>
<% else %>
  <p class="nomore">検索結果は以上です</p>
<% end %>

app/views/contests/_contests_ajax.html.erb
<% if contests.present? %>
  <ul class="contests-container">
    <% if contests.present? %>
      <%= render partial: 'contests/contest', collection: contests %>
    <% end %>
  </ul>
  <% if contests.last_page? || contests.out_of_range? %>
    <p class="nomore">検索結果は以上です</p>
  <% else %>
    <%= link_to 'もっと見る', contests_index_ajax_path('target' => target, 'page' => contests.next_page), remote: true, class: 'js-loading-trigger', data: {target: target} %>
  <% end %>

<% else %>
  <p class="nomore">検索結果は以上です</p>
<% end %>

app/views/contests/_copy_url.html.erb
<p class="contest__info-label"><%= url.copy_label %>の限定公開URL</p>
<div class="contest__info-p copy_url">
  <p class="contest__info-urlbox" id="contest__info-copy_text-<%= url.page %>"><%= url.url_value %></p>
  <%= form_with model: url, url: url_path, method: 'patch', autocapitalize: 'none', class: 'contest__info-copy_form' do |f| %>
    <%= f.hidden_field :id, value: url.contest_id %>
    <%= f.hidden_field :page, value: url.page %>
    <%= f.submit '更新する', id: "contest__info-copy_submit-#{url.page}" ,data: { "disable-with": '更新中です' } %>
  <% end %>
</div>

app/views/contests/_form.html.erb
<% @form_options ||= Contest.form_options %>
<div class="contestCreate__form-container">
  <%= render  "shared/error_messages", model: contest %>
  <%= form_with model: contest, url: url, local: true, class:'contestCreate__form-body', autocapitalize: 'none' do |f| %>
    <h3 class="contestCreate__form-classification">コンテスト情報</h3>
    <div class="contestCreate__form-classificationContainer">
      <div class="contestCreate__form-group">
        <%= f.label :name, 'コンテスト名', class: 'contestCreate__form-label' %>
        <%= f.text_field :name, class: 'contestCreate__form-input', autocomplete: 'off' %>
      </div>
      <div class="contestCreate__form-group">
        <%= f.label :description, 'コンテストの説明', class: 'contestCreate__form-label' %>
        <%= f.text_area :description, class: 'contestCreate__form-input', autocomplete: 'off' %>
      </div>
    </div>


    <h3 class="contestCreate__form-classification">期間の設定</h3>
    <div class="contestCreate__form-classificationContainer">
      <% @form_options[0].each do |key, value| %>
        <div class="contestCreate__form-group">
          <%= f.label key, value[:label], class: 'contestCreate__form-label' %>
          <div class="contestCreate__form-datetime-container">
            <div class="contestCreate__form-datetime-start">
              <%= f.date_field value[:start][:obj] + '_date', value: print_date_for_form(contest.send(value[:start][:obj])), class: 'contestCreate__form-input-date', autocomplete: 'off' %>
              <%= f.time_field value[:start][:obj] + '_time', value: print_time_for_form(contest.send(value[:start][:obj])), class: 'contestCreate__form-input-time', autocomplete: 'off' %>
            </div>
            <div class="contestCreate__form-datetime-end">
              <i class="fas fa-long-arrow-alt-right contestCreate__form-datetime-icon"></i>
              <%= f.date_field value[:end][:obj] + '_date', value: print_date_for_form(contest.send(value[:end][:obj])), class: 'contestCreate__form-input-date', autocomplete: 'off' %>
              <%= f.time_field value[:end][:obj] + '_time', value: print_time_for_form(contest.send(value[:end][:obj])), class: 'contestCreate__form-input-time', autocomplete: 'off' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <h3 class="contestCreate__form-classification">公開範囲の設定</h3>
    <div class="contestCreate__form-classificationContainer">
      <% @form_options[1].each do |key, value| %>
        <div class="contestCreate__form-group">
          <%= f.label key, value[:label], class: 'contestCreate__form-label' %>
          <%= f.select key, value[:options], {}, {class: 'contestCreate__form-input-select', autocomplete: 'off'} %>
        </div>
      <% end %>
    </div>

    <h3 class="contestCreate__form-classification">その他の設定</h3>
    <div class="contestCreate__form-classificationContainer">
      <div class="contestCreate__form-group row">
        <%= f.label :num_of_submit_limit, '提出する作品数の制限', class: 'contestCreate__form-label' %>
        <div>
          <%= f.number_field :num_of_submit_limit, step: 1, min: 1, max: 99, class: 'contestCreate__form-input-num', autocomplete: 'off' %>
          <span>つまで</span>
        </div>
      </div>
      <div class="contestCreate__form-group row">
        <%= f.label :voting_points, '投票者の持ち点', class: 'contestCreate__form-label' %>
        <div>
          <%= f.number_field :voting_points, step: 1, min: 1, max: 99, class: 'contestCreate__form-input-num', autocomplete: 'off' %>
          <span>pt</span>
        </div>
      </div>
      <div class="contestCreate__form-group row">
        <%= f.label :num_of_views_in_result, '表示する順位', class: 'contestCreate__form-label' %>
        <div>
          <%= f.number_field :num_of_views_in_result, step: 1, min: 1, max: 99, class: 'contestCreate__form-input-num', autocomplete: 'off' %>
          <span>位まで</span>
        </div>

      </div>
      <% @form_options[2].each do |key, value| %>
        <div class="contestCreate__form-group">
          <%= f.label key, value[:label], class: 'contestCreate__form-label' %>
          <%= f.select key, value[:options], {}, {class: 'contestCreate__form-input-select', autocomplete: 'off'} %>
        </div>
      <% end %>
    </div>
    <%= f.submit submit_message %>
  <% end %>
</div>

app/views/contests/_links.html.erb
<% content_tag_options_for_contest_links(contest, 'contest__header-link').each do |link_options| %>
  <% if link_options[:tag] == 'menu' %>
    <%= content_tag(:div, link_options[:options]) do %>
      <%= link_options[:content] %>

      <div id="menu_photos" class="menu">
        <% if @user_photos.present? %>
          <ul>
            <% @user_photos.each do |photo| %>
              <li><%= link_to photo.excerpt_name, edit_contest_photo_path(contest, photo) %></li>
            <% end %>
          </ul>
        <% else %>
          <p>作品の取得に失敗しました</p>
        <% end %>
      </div>
    <% end %>

  <% else %>
    <%= content_tag(link_options[:tag], link_options[:content], link_options[:options]) %>
  <% end %>

<% end %>

app/views/contests/_tab.html.erb
<div id="tab-body-<%= target %>">
  <%= render 'contests/contests_ajax', contests: contests, target: target %>
</div>

app/views/contests/_tab_container.html.erb
<%

# タブを追加する手順
# 1. .tab-linksに項目を追加
#   <li><a href="#contests_new">最新のコンテスト</a></li>
# 2. .tabにタブを追加
#   <div id="contests_submited" class="tab">
#     <%= render "contests/tab", contests: @contests_submited, target: 'contests_submited' % >
#   </div>

%>
<div class="tab-container">
  <ul class="tab-links">
    <li><a href="#contests_new"><%= t 'contests.index.contests_new' %></a></li>
    <li><a href="#contests_submited"><%= t 'contests.index.contests_submited' %></a></li>
  </ul>

  <div id="contests_new" class="tab">
    <%= render "contests/tab", contests: @contests, target: 'contests' %>
  </div>

  <div id="contests_submited" class="tab">
    <%= render "contests/tab", contests: @contests_submited, target: 'contests_submited' %>
  </div>
</div>

app/views/contests/contests_ajax.html.erb
<ul class="contests-container">
  <% if contests.present? %>
    <%= render partial: 'contests/contest', collection: contests %>
  <% end %>
</ul>
<% if contests.last_page? || contests.out_of_range? %>
  <p>検索結果は以上です</p>
<% else %>
  <%= link_to_next_page contests, 'もっと見る', remote: true, class: 'js-loading-trigger', id: "loading-container-#{target}", data: {target: target} %>
<% end %>

app/views/contests/edit.html.erb
<% provide(:title, 'コンテストの編集') %>

<h1 class="contestEdit-title">コンテストの編集</h1>
<%= render  "form", contest: @contest, url: contest_path(@contest), submit_message: 'コンテストを編集' %>

app/views/contests/index.html.erb
<% provide(:aside_type, 'flex') %>
<% content_for :aside do %>
  <% if user_signed_in? %>
    <li class="aside__item-container">
      <div class="aside__item__header-container">
        <h3><%= t 'aside.title.photo_submited' %></h3>
      </div>
      <div class="aside__item__body-container">
        <div class="aside__item__body-main">
          <h4 class="aside__item__body-title"></h4>
          <table class="aside__item__body-table">
            <thead>
              <tr>
                <th><%= t 'aside.table.date_vote_end' %></th>
                <th><%= t 'aside.table.photo_title' %></th>
              </tr>
            </thead>
            <% if @submited_photos.present? %>
              <tbody>
                <%= render partial: "shared/aside_table_photo", collection: @submited_photos, as: 'photo' %>
              </tbody>
            <% else %>
              <tbody>
                <tr><td>-</td><td><%= t 'aside.table.no_photos' %></tr></td>
              </tbody>
            <% end %>
          </table>
        </div>
      </div>
    </li>
  <% else %>
    <li class="aside__item-container">
      <div class="aside__item__header-container">
        <h3><%= t 'aside.user.no_login' %></h3>
      </div>
      <div class="aside__item__body-container">
        <div class="aside__item__body-main">
          <p class="contestlist__aside-p"><%= t 'aside.user.guide_login_page' %></p>
          <%= link_to t('user.signup'), new_user_registration_path, class: 'contestlist__aside-link' %>
          <%= link_to t('user.login'), new_user_session_path, class: 'contestlist__aside-link' %>
        </div>
      </div>
    </li>
  <% end %>
<% end %>

<div class="contestlist__header-container">
  <h2 class="contestlist__header-title"><%= t '.title' %></h2>
  <%= link_to new_contest_path, class: 'contestlist__header-newlink' do %>
    <i class="contestlist__header-newlink-icon fas fa-plus-circle"></i>
    <p class="contestlist__header-newlink-value"><%= t '.contest_create' %></p>
  <% end %>
</div>

<div class="contestlist__body-container">
  <%= render 'contests/tab_container' %>
</div>

app/views/contests/index_ajax.js.erb
$('#tab-body-<%= @target %> .loading-container').remove();
<% if @contests %>
  $("#tab-body-<%= @target %>").append("<%= j(render  "contests_ajax", contests: @contests, target: @target) %>");
<% else %>
  $("#tab-body-<%= @target %>").append($('<div>', { text:'コンテストは見つかりませんでした' }));
<% end %>

app/views/contests/new.html.erb
<% provide(:title, 'コンテスト作成') %>

<h1 class="contestCreate-title">新しいコンテストを作成</h1>
<%= render  "form", contest: @contest, url: contests_path, submit_message: 'コンテストを作成' %>