config/routes.rb
Rails.application.routes.draw do

  #ルート++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  root 'contests#index'
  #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  #コンテスト+++++++++++++++++++++++++++++++++++++++++++++++++++++
  #index無限スクロール
  get 'contests/more', to: 'contests#index_ajax', as: 'contests_index_ajax'
  resources :contests, except: [:index] do
    #コンテストに紐付けられた写真
    resources :photos
    #コンテストに紐付けられた投票
    resources :votes, only: [:index, :new, :create, :destroy]
  end
  #+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  #ユーザ++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  devise_for(
    :users,
    path: '',
    module: 'users',
    path_names: { registration: 'users' }
  )
  devise_scope :user do
    get 'users/:id', to: 'users/registrations#show', as: 'user'
  end
  #+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  #ユーザに紐付けられた写真++++++++++++++++++++++++++++++++++++++++
  resources :users, only: [] do
    resources :photos, only: [:show, :edit, :update, :destroy]
  end
  #+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  #限定公開URL制御+++++++++++++++++++++++++++++++++++++++++++++++++
  patch 'url', to: 'urls#update'
  #+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  #管理画面+++++++++++++++++++++++++++++++++++++++++++++++++++++++
  get 'contests/:contest_id/admin', to: 'admin#index', as: 'admin'
  delete 'contests/:contest_id/admin/photo/:id', to: 'admin#photo_delete', as: 'admin_photo'

  #静的ページ+++++++++++++++++++++++++++++++++++++++++++++++++++++
  get 'aboutus', to: 'static_pages#aboutus'
  #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
end

app/views/shared/_aside_table_contest.html.erb
<tr>
  <td>
    <p class="aside__item__body-table_date"><%= print_date_with_wday(contest.vote_end_at) %></p>
    <p class="aside__item__body-table_time"><%= print_time_for_form(contest.vote_end_at) %></p>
  </td>
  <td><%= link_to contest.name, contest_path(contest), class: 'aside__item__body-table_name' %></td>
</tr>

app/views/shared/_aside_table_photo.html.erb
<tr>
  <td>
    <%= link_to contest_path(photo.contest) do %>
      <p class="aside__item__body-table_date"><%= print_date_with_wday(photo.contest.vote_end_at) %></p>
      <p class="aside__item__body-table_time"><%= print_time_for_form(photo.contest.vote_end_at) %></p>
    <% end %>
  </td>
  <td><%= link_to photo.name, contest_photo_path(photo.contest, photo), class: 'aside__item__body-table_name' %></td>
</tr>

app/views/shared/_debug.html.erb
<% if @debug %>
  <h1 id="debug">デバッグ</h1>
  <%= @debug %>
  <style>
    #debug{
      font-size: 1.4rem;
      font-weight: bold;
    }
  </style>
<% end %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(model.errors.count, "error") %>.
    </div>
    <ul>
      <% model.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_modal_form.html.erb
<a class="js-modal-open modal-label" data-target="modal__window"><%= link_message %></a>
<div id="modal__window" class="modal__window js-modal">
  <div class="modal__bg js-modal-close"></div>
  <div class="modal__content">

    <h3 class="modal__content-title">Alert</h3>
    <p class="modal__content-body"><%= modal_message %></p>
    <ul class="modal__icon-list">
      <li class="modal__icon-container">
        <%= link_to link, method: method, class: 'modal__icon-yes-link' do %>
          <span class="modal__icon-yes-content"></span>
        <% end %>
      </li>
      <li class="modal__icon-container">
        <a class="js-modal-close modal__icon-no-link" data-target="modal__window">
          <span class="modal__icon-no-content"></span>
        </a>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_modal_photo.html.erb
<div id="modal_photo_<%= photo.id %>" class="modal__photo__window">
  <div class="modal__photo__bg js-modal-close" data-target="<%= "modal_photo_#{photo.id}" %>"></div>
  <div class="modal__photo__content">
    <div class="modal__photo-grid">

      <div class="modal__photo__title-container">
        <%= link_to photo.name, path_for_photo(photo), class: 'modal__photo__title-content' %>
      </div>

      <div class="modal__photo__links-container">
        <% if controller.controller_name == 'admin' %>
          <%= render 'shared/modal_form', link_message: '[この作品を削除]', modal_message: "作品名：#{photo.name}を削除しますか？※除外ではなく削除です", link: admin_photo_path(@contest, photo), method: 'delete' %>
        <% end %>
        <div class="modal__photo__links-icon_container js-modal-close" data-target="<%= "modal_photo_#{photo.id}" %>">
          <i class="fas fa-times modal__photo__links-icon_close"></i>
        </div>
      </div>

      <div class="modal__photo__body-container">
        <div class="modal__photo__body-img_container">
          <%= image_tag "", class: 'modal__photo__body-img_image', id: "js-photo-target-#{photo.id}" %>
        </div>
      </div>

      <div class="modal__photo__info-container">
        <div class="modal__photo__info-group work">
          <div class="modal__photo__info-wrapper">
            <p class="modal__photo__info-p">タイトル：<%= photo.name %></p>
            <p class="modal__photo__info-p">説明：<%= photo.description %></p>
          </div>
        </div>

        <% if controller.controller_name == 'admin' || photo.contest.is_after_period_voting? %>
        <div class="modal__photo__info-group photo">
          <div class="modal__photo__info-wrapper">
            <% if controller.controller_name == 'admin' || (controller.controller_name == 'votes' && [0, 1].include?(photo.contest.visible_setting_for_user_name)) || (controller.controller_name == 'photos' && [1].include?(photo.contest.visible_setting_for_user_name)) %>
              <p class="modal__photo__info-p">作者：<%= photo.user.name %></p>
            <% end %>
            <p class="modal__photo__info-p">カメラ：<%= photo.camera %></p>
            <p class="modal__photo__info-p">レンズ：<%= photo.lens %></p>
            <p class="modal__photo__info-p">ISO：<%= photo.iso %></p>
            <p class="modal__photo__info-p">F値：<%= photo.aperture %></p>
            <p class="modal__photo__info-p">シャッター速度：<%= photo.shutter_speed %></p>
          </div>
        </div>
        <% end %>
      </div>

    </div>
  </div>
</div>