config/routes.rb
Rails.application.routes.draw do

  #ルート++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  root 'contests#index'
  #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  #コンテスト+++++++++++++++++++++++++++++++++++++++++++++++++++++
  #index無限スクロール
  get 'contests/more', to: 'contests#index_ajax', as: 'contests_index_ajax'
  resources :contests, except: [:index] do
    #コンテストに紐付けられた写真
    resources :photos
    #コンテストに紐付けられた投票
    resources :votes, only: [:index, :new, :create, :destroy]
  end
  #+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  #ユーザ++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  devise_for(
    :users,
    path: '',
    module: 'users',
    path_names: { registration: 'users' }
  )
  devise_scope :user do
    get 'users/:id', to: 'users/registrations#show', as: 'user'
  end
  #+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  #ユーザに紐付けられた写真++++++++++++++++++++++++++++++++++++++++
  resources :users, only: [] do
    resources :photos, only: [:show, :edit, :update, :destroy]
  end
  #+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  #限定公開URL制御+++++++++++++++++++++++++++++++++++++++++++++++++
  patch 'url', to: 'urls#update'
  #+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  #管理画面+++++++++++++++++++++++++++++++++++++++++++++++++++++++
  get 'contests/:contest_id/admin', to: 'admin#index', as: 'admin'
  delete 'contests/:contest_id/admin/photo/:id', to: 'admin#photo_delete', as: 'admin_photo'

  #静的ページ+++++++++++++++++++++++++++++++++++++++++++++++++++++
  get 'aboutus', to: 'static_pages#aboutus'
  #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :contest
  belongs_to :user
  has_many :votes, dependent: :destroy
  mount_uploader :image, ImageUploader
  DEFAULT_FILE_NAME = 'cat_S.jpg'

  #投票結果表示で使う
  attr_accessor :vote_points
  attr_accessor :vote_rank

  scope :public_all, -> (time = Time.current){ left_joins(:contest).after_vote.where('`contests`.`visible_range_show` <= 0 OR `contests`.`visible_range_result` <= 0') }
  scope :after_vote, -> (time = Time.current){ left_joins(:contest).where('`contests`.`vote_end_at` <= ?', time) }

  # #===nameカラム===========================================================
  before_save { self.name = name.gsub(/\A[[:space:]]+|[[:space:]]\z/, "") }
  validates :name,  presence: true,
                    length: { maximum: 255, allow_blank: true }
  # #========================================================================
  # #===descriptionカラム====================================================
  before_save { self.description = '' if self.description.nil? }
  validates :description, presence: false,
                          length: { maximum: 10000 }
  # #========================================================================
  # #===camera, lens, iso, aperture, shutter_speedカラム=====================
  with_options presence: true, length: {maximum: 255} do
    validates :camera
    validates :lens
    validates :iso
    validates :aperture
    validates :shutter_speed
  end
  # #========================================================================
  # #===descriptionカラム====================================================
  validates :image, presence: true
  # #========================================================================


  def excerpt_name(i = 15)
    name = self.name
    name.length > i ? name[0..i-1] + '...' : name
  end

  def attach_default_image
    if !self.image.attached?
      self.image.attach(io: File.open('app/assets/images/cat_S.jpg'), filename: 'cat_S.jpg', content_type: 'image/jpeg')
    end
  end

  def self.model_labels
    {
      image: '写真',
      name: '作品名',
      description: '作品の説明',
      photographer: '撮影者',
      camera: 'カメラ',
      lens: 'レンズ',
      iso: 'ISO',
      aperture: 'F値',
      shutter_speed: 'シャッター速度',
    }
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :check_logged_in, except: [:index, :show]
  before_action :check_correct_user, only: [:edit, :update, :destory]
  before_action :check_able_to_submit, only: [:new, :create]
  before_action :check_able_to_edit, only: [:edit, :update, :destroy]

  def index
    @contest ||= Contest.find_contest_show(params[:contest_id])
    redirect_back fallback_location: root_path, danger: 'コンテストの取得に失敗しました' and return unless @contest
    redirect_back fallback_location: @contest, danger: '閲覧可能期間外です' and return unless @contest.is_in_period_show?
    if @contest.visible_setting_for_user_name.to_s == '1'
      @photos = @contest.photos.order('id ASC').includes(:user)
    else
      @photos = @contest.photos.order('id ASC')
    end
  end

  def show
    @photo = Photo.eager_load(:user, :contest).find_by(id: params[:id])
    redirect_back fallback_location: root_path, danger: '作品の取得に失敗しました' and return unless @photo
  end

  def new
    @contest ||= Contest.find_contest_entry(params[:contest_id])
    @photo = Photo.new
  end

  def create
    @contest ||= Contest.find_contest_entry(params[:contest_id])
    @photo = @contest.photos.build(photo_params)
    if @photo && @photo.save
      redirect_to @contest, success: '作品を提出しました'
    else
      flash.now[:danger] = '作品の提出に失敗しました'
      render :new and return
    end
  end

  def edit
    @contest ||= Contest.find_by(id: params[:contest_id])
    @photo ||= Photo.find_by(id: params[:id])

    unless @contest
      flash[:danger] = 'コンテストの取得に失敗しました'
      redirect_back fallback_location: root_path and return
    end

    unless @photo
      flash[:danger] = '作品の取得に失敗しました'
      redirect_back fallback_location: root_path and return
    end
  end

  def update
    @photo ||= Photo.find_by(id: params[:id])
    redirect_to root_path, danger: '作品の取得に失敗しました' and return unless @photo
    if @photo.update(photo_params)
      redirect_to contest_photo_path(@photo.contest_id, @photo), success: '作品の更新に成功しました' and return
    else
      flash.now[:danger] = '作品の編集に失敗しました'
      render :edit and return
    end
  end

  def destroy
    @photo ||= Photo.find_by(id: params[:id])
    redirect_to root_path, danger: '作品の取得に失敗しました' and return unless @photo

    if @photo.destroy
      flash[:success] = '作品の削除に成功しました'
      redirect_to path_for_redirect_from_photo_delete and return
    else
      flash[:danger] = '作品の削除に失敗しました'
      redirect_to path_for_photo(@photo) and return
    end
  end

  private
    def photo_params
      params.require(:photo).permit(
        :name, :description,
        :camera, :lens,
        :iso, :aperture, :shutter_speed, :image
        ).merge(user: current_user)
    end

    def check_able_to_submit
      @contest ||= Contest.find_contest_entry(params[:contest_id])
      redirect_back fallback_location: root_path, danger: 'コンテストの取得に失敗しました' and return unless @contest
      redirect_back fallback_location: @contest, danger: '作品を既に規定数提出したか、募集期間外です' and return unless @contest.is_able_to_submit?(current_user)
    end

    def check_correct_user
      @photo ||= Photo.find_by(id: params[:id])
      redirect_back fallback_location: root_path, danger: '作品の取得に失敗しました' and return unless @photo
      @user = @photo.user
      redirect_back fallback_location: root_path, danger: '現在のユーザはこの作品の作成者ではありません' and return unless correct_user?(@user)
    end

    def check_able_to_edit
      @contest ||= Contest.find_contest_entry(params[:contest_id])
      @contest ||= Photo.find_by(id: params[:id]).contest unless @contest
      redirect_back fallback_location: root_path, danger: 'コンテストの取得に失敗しました' and return unless @contest
      redirect_back fallback_location: @contest, danger: '投票開始時刻を過ぎているので作品の編集はできません' and return if @contest.is_after_period_voting?
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
  def path_for_photo(photo, method = nil)
    if @model_for_path.nil?
      user_or_contest_id = params[:contest_id] || params[:user_id] || params[:id]
      model = Contest.find_by(id: user_or_contest_id) || User.find_by(id: user_or_contest_id)
      @model_for_path = {class: model.class.to_s, id: user_or_contest_id}
    end

    if method.nil?
      return contest_photo_path(@model_for_path[:id], photo.id) if @model_for_path[:class] == 'Contest'
      return user_photo_path(@model_for_path[:id], photo.id) if @model_for_path[:class] == 'User'
    elsif method == 'edit'
      return edit_contest_photo_path(@model_for_path[:id], photo.id) if @model_for_path[:class] == 'Contest'
      return edit_user_photo_path(@model_for_path[:id], photo.id) if @model_for_path[:class] == 'User'
    elsif method == 'new'
      return edit_contest_photo_path(@model_for_path[:id], photo.id) if @model_for_path[:class] == 'Contest'
      return edit_user_photo_path(@model_for_path[:id], photo.id) if @model_for_path[:class] == 'User'
    elsif method == 'form'
      return contest_photos_path(@model_for_path[:id]) if !photo.id.present?
      return contest_photo_path(@model_for_path[:id], photo.id) if @model_for_path[:class] == 'Contest'
      return user_photo_path(@model_for_path[:id], photo.id) if @model_for_path[:class] == 'User'
    end
  end

  def path_for_redirect_from_photo_delete
    return contest_path(params[:contest_id]) if params[:contest_id].present?
    return user_path(params[:user_id]) if params[:user_id].present?
  end
end

app/views/photos/_form.html.erb
<% @labels ||= Photo.model_labels %>
<div class="photoCreate__form-container">
  <%= form_with model: photo, url: path_for_photo(photo, 'form'), local: true, class:'photoCreate__form-body', autocapitalize: 'none' do |f| %>
    <h3 class="photoCreate__form-classification">作品情報</h3>
    <div class="photoCreate__form-classificationContainer">

      <%= tag.div class: 'photoCreate__form-preview-imgcontainer', style: photo.image.file.nil? ? 'display: none;' : '' do %>
        <%= image_tag photo.image.file.nil? ? '' : photo.image.url, class: 'photoCreate__form-preview-img', alt: 'プレビュー画像' %>
      <% end %>
      <div class="photoCreate__form-group photoCreate__form-preview-group">
        <%= f.label :image, @labels[:image], class: 'photoCreate__form-label' %>
        <%= f.file_field :image, id: 'photoFileField', class:'photoCreate__form-input', accept: 'image/jpg, image/jpeg, image/png' %>
      </div>

      <div class="photoCreate__form-group">
        <%= f.label :name, @labels[:name], class: 'photoCreate__form-label' %>
        <%= f.text_field :name, class: 'photoCreate__form-input', autocomplete: 'off' %>
      </div>

      <div class="photoCreate__form-group">
        <%= f.label :description, @labels[:description], class: 'photoCreate__form-label' %>
        <%= f.text_area :description, id: 'form_description', class: 'photoCreate__form-input', autocomplete: 'off' %>
      </div>
    </div>

    <h3 class="photoCreate__form-classification">写真情報</h3>
    <div class="photoCreate__form-classificationContainer">
      <div class="photoCreate__form-group">
        <%= f.label :camera, @labels[:camera], class: 'photoCreate__form-label' %>
        <%= f.text_field :camera, id: 'form_camera', class: 'photoCreate__form-input', autocomplete: 'off' %>
      </div>

      <div class="photoCreate__form-group">
        <%= f.label :lens, @labels[:lens], class: 'photoCreate__form-label' %>
        <%= f.text_field :lens, id: 'form_lens', class: 'photoCreate__form-input', autocomplete: 'off' %>
      </div>

      <div class="photoCreate__form-group">
        <%= f.label :iso, @labels[:iso], class: 'photoCreate__form-label' %>
        <%= f.text_field :iso, id: 'form_iso', class: 'photoCreate__form-input', autocomplete: 'off' %>
      </div>

      <div class="photoCreate__form-group">
        <%= f.label :aperture, @labels[:aperture], class: 'photoCreate__form-label' %>
        <%= f.text_field :aperture, id: 'form_aperture', class: 'photoCreate__form-input', autocomplete: 'off' %>
      </div>

      <div class="photoCreate__form-group">
        <%= f.label :shutter_speed, @labels[:shutter_speed], class: 'photoCreate__form-label' %>
        <%= f.text_field :shutter_speed, id: 'shutter_speed', class: 'photoCreate__form-input', autocomplete: 'off' %>
      </div>
    </div>

    <%= f.submit %>
  <% end %>
</div>

app/views/photos/_photo.html.erb
<li class="photolist__item-container">
  <div class="photolist__item-img_square">
    <div class="photolist__item-img_container">
      <a class="photolist__item-img_link js-modal-open js-load-photo" data-photo_url="<%= photo.image.url %>" data-photo_target="<%= "js-photo-target-#{photo.id}" %>" data-target="<%= "modal_photo_#{photo.id}" %>">
        <%= image_tag photo.image.thumb.url, class: 'photolist__item-img_image' %>
      </a>
    </div>
  </div>

  <% if defined? f %>
    <div class="photolist__item-info_container">
      <a class="photolist__item-info_name js-modal-open js-load-photo" data-photoURL="<%= photo.image.url %>" data-photoTarget="<%= "js-photo-target-#{photo.id}" %>" data-target="<%= "modal_photo_#{photo.id}" %>"><%= photo.name %></a>
      <%= f.number_field "vote[#{photo.id}]", step: 1, min: 0, max: contest.voting_points, autocomplete: 'off', class: 'photolist__item-vote_input', id: photo.id %>
    </div>
  <% else %>
    <div class="photolist__item-info_container">
      <a class="photolist__item-info_name_fill js-modal-open js-load-photo" data-photoURL="<%= photo.image.url %>" data-photoTarget="<%= "js-photo-target-#{photo.id}" %>" data-target="<%= "modal_photo_#{photo.id}" %>"><%= photo.name %></a>
    </div>
  <% end %>
</li>
<%= render 'shared/modal_photo', photo: photo %>

app/views/photos/_photos.html.erb
<% if @photos.present? %>
  <%= paginate @photos, param_name: "page_photos" %>
  <ul class="user__photoslist-container">
    <%= render partial: 'photos/photo', collection: @photos %>
  </ul>
  <%= paginate @photos, param_name: "page_photos" %>
<% else %>
  <ul class="user__photoslist-container">
    <p>作品が見つかりません</p>
  </ul>
<% end %>

app/views/photos/edit.html.erb
<% provide(:title, '作品の編集') %>
<% provide(:aside_type, 'flex') %>
<% content_for :aside do %>

  <li class="aside__item-container">
      <div class="aside__item__header-container">
        <h3 class="aside__item__header-title">コンテストの情報</h3>
      </div>
      <div class="aside__item__body-container">
        <div class="photoEdit__aside__contest-container">
          <h4 class="photoEdit__aside__contest-name">コンテスト名：<%= link_to @contest.name, contest_path(@contest) %></h4>
          <p class="photoEdit__aside__contest-p">説明：<%= @contest.description %></p>
        </div>
      </div>
    </li>

<% end %>

<h1 class="photoEdit-title">作品の編集</h1>

<%= render  "form", photo: @photo, url: path_for_photo(@photo) %>

app/views/photos/index.html.erb
<% provide(:title, "作品一覧 #{@contest.name}") %>

<div class="photos-container">
  <div class="photos-title_container">
    <h1 class="photos-title">作品一覧</h1>
    <p class="photos-title_sub"><%= @contest.name %></p>
  </div>
  <div class="photos__body-container">
    <% if @photos.present? %>
      <ul class="photos__body-img_container">
        <%= render partial: 'photos/photo', collection: @photos %>
      </ul>
      <h3 class="photos__body-title">その他</h3>
      <div class="photos__body-link_container">
        <%= link_to  "投票結果", contest_votes_path(@contest), class: 'photos__body-link' %>
      </div>

    <% else %>
      <div class="photos__body-no_image">作品が投稿されていません</div>
    <% end %>
  </div>
</div>

app/views/photos/new.html.erb
<% provide(:title, '作品提出フォーム') %>
<% provide(:aside_type, 'flex') %>

<% content_for :aside do %>
  <li class="aside__item-container">
      <div class="aside__item__header-container">
        <h3 class="aside__item__header-title">コンテストの情報</h3>
      </div>
      <div class="aside__item__body-container">
        <div class="aside__item__body-group">
          <p class="aside__item__body-label">コンテスト名</p>
          <p class="aside__item__body-p"><%= @contest.name %></p>
        </div>

        <div class="aside__item__body-group">
          <p class="aside__item__body-label">コンテストの説明</p>
          <p class="aside__item__body-p"><%= @contest.description %></p>
        </div>

        <div class="aside__item__body-group">
          <p class="aside__item__body-label">作品の応募期間</p>
          <p class="aside__item__body-p"><%= @contest.entry_start_at.to_s(:datetime_jp) %></p>
          <p class="aside__item__body-p"> ～ <%= @contest.entry_end_at.to_s(:datetime_jp) %></p>
        </div>
      </div>
    </li>
<% end %>

<h1 class="photoCreate-title">作品の提出フォーム</h1>

<div class="accordion-container photoCreate-accordion_contest_info">
  <div class="accordion__title-container js-body-accordion-open" data-target="js_accordion_contest_info" data-icon="js_accordion_contest_info_icon">
    <i class="fas fa-caret-down accordion__title-icon" id="js_accordion_contest_info_icon"></i>
    <h4 class="accordion__title-content">コンテストの情報</h4>
  </div>

  <div id='js_accordion_contest_info' class="accordion__body-container">

    <div class="accordion__body-group">
      <p class="accordion__body-label">コンテスト名</p>
      <p class="accordion__body-p"><%= @contest.name %></p>
    </div>

    <div class="accordion__body-group">
      <p class="accordion__body-label">コンテストの説明</p>
      <p class="accordion__body-p"><%= @contest.description %></p>
    </div>

    <div class="accordion__body-group">
      <p class="accordion__body-label">作品の応募期間</p>
      <p class="accordion__body-p"><%= @contest.entry_start_at.to_s(:datetime_jp) %> ～ <%= @contest.entry_end_at.to_s(:datetime_jp) %></p>
    </div>
  </div>
</div>

<%= render  "form", photo: @photo, url: contest_photos_path(params[:contest_id]) %>

app/views/photos/show.html.erb
<% provide(:title, @photo.name) %>

<div class="photo-container">
  <div class="photo__img-container">
    <%= image_tag @photo.image.url, class: 'photo__img-image' %>
  </div>

  <div class="photo__info-container">
    <h3 class="photo__info-classification">作品情報</h3>
    <div class="photo__info-classificationContainer">
      <p class="photo__info-p">コンテスト名：<%= link_to @photo.contest.name, @photo.contest %></p>
      <p class="photo__info-p">タイトル：<%= link_to @photo.name, path_for_photo(@photo) %></p>
      <p class="photo__info-p">説明：<%= @photo.description %></p>
    </div>

    <h3 class="photo__info-classification">写真情報</h3>
    <div class="photo__info-classificationContainer">
      <p class="photo__info-p">カメラ：<%= @photo.camera %></p>
      <p class="photo__info-p">レンズ：<%= @photo.lens %></p>
      <p class="photo__info-p">ISO：<%= @photo.iso %></p>
      <p class="photo__info-p">絞り：<%= @photo.aperture %></p>
      <p class="photo__info-p">シャッター速度：<%= @photo.shutter_speed %></p>
    </div>

    <% if correct_user?(@photo.user) %>
      <h3 class="photo__info-classification">作成者用リンク</h3>
      <div class="photo__info-classificationContainer">
        <% if @photo.contest.is_after_period_voting? %>
          <p>[この作品の編集、削除期間は過ぎています]</p>
        <% else %>
          <%= link_to  "この作品を編集", path_for_photo(@photo, 'edit') %>
          <%= render 'shared/modal_form', link_message: 'この作品を削除', modal_message: "作品名：#{@photo.name}を削除しますか？", link: path_for_photo(@photo), method: 'delete' %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>