config/routes.rb
Rails.application.routes.draw do

  #ルート++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  root 'contests#index'
  #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  #コンテスト+++++++++++++++++++++++++++++++++++++++++++++++++++++
  #index無限スクロール
  get 'contests/more', to: 'contests#index_ajax', as: 'contests_index_ajax'
  resources :contests, except: [:index] do
    #コンテストに紐付けられた写真
    resources :photos
    #コンテストに紐付けられた投票
    resources :votes, only: [:index, :new, :create, :destroy]
  end
  #+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  #ユーザ++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  devise_for(
    :users,
    path: '',
    module: 'users',
    path_names: { registration: 'users' }
  )
  devise_scope :user do
    get 'users/:id', to: 'users/registrations#show', as: 'user'
  end
  #+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  #ユーザに紐付けられた写真++++++++++++++++++++++++++++++++++++++++
  resources :users, only: [] do
    resources :photos, only: [:show, :edit, :update, :destroy]
  end
  #+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  #限定公開URL制御+++++++++++++++++++++++++++++++++++++++++++++++++
  patch 'url', to: 'urls#update'
  #+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  #管理画面+++++++++++++++++++++++++++++++++++++++++++++++++++++++
  get 'contests/:contest_id/admin', to: 'admin#index', as: 'admin'
  delete 'contests/:contest_id/admin/photo/:id', to: 'admin#photo_delete', as: 'admin_photo'

  #静的ページ+++++++++++++++++++++++++++++++++++++++++++++++++++++
  get 'aboutus', to: 'static_pages#aboutus'
  #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
end

app/views/layouts/_aside.html.erb
<% if content_for?(:aside) %>
  <%= yield(:aside) %>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <%= tag.div value, class: key, id: 'flash_message' %>
  <div id="flash_close" class="js-flash-close" data-target="flash_container">
    <i class="fas fa-times"></i>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer-container">

  <div class="footer-body">
    <div class="footer-center">
      <p class="footer-copyright">&copy; 2021 SaidaiPhoto</p>
      <%= link_to 'このアプリについて', aboutus_path, class: 'footer-link' %>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header-container">
  <nav class="header__nav-container">
    <ul class="header__nav-ul">
      <li class="header__nav-li"><%= link_to  "PhotoContest", root_path, class: 'header__nav-title' %></li>
      <% if user_signed_in? %>
        <li class="header__nav-li">
          <%= render 'layouts/header_accordion' %>
        </li>
      <% else %>
        <li class="header__nav-li">
          <div class="header__nav-li_container">
            <%= link_to 'このアプリについて', aboutus_path, class: 'header__nav-li-item inactive-mobile' %>
            <%= link_to '新規登録', new_user_registration_path, class: 'header__nav-li-item' %>
            <%= link_to 'ログイン', new_user_session_path, class: 'header__nav-li-item' %>
          </div>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_header_accordion.html.erb
<div class="header__nav-accordionmenu-container">
  <div class="header__nav-accordionmenu-label js-AccordionMenu">
    <div class="header__nav-accordionmenu-value">
      <%= image_tag current_user.image.url, class: 'header__nav-accordionmenu-value-img' %>
      <p class="header__nav-accordionmenu-value-name"><%= current_user.name %></p>
    </div>
    <i class="header__nav-accordionmenu-icon fas fa-chevron-down"></i>
  </div>
  <div class="header__nav-accordionmenu-window" style="display: none;">
    <div class="header__nav-accordionmenu-contents">
      <%= link_to  "ユーザページ", user_path(current_user), class: 'header__nav-accordionmenu-item' %>
      <%= link_to  "プロフィールを編集", edit_user_registration_path(current_user), class: 'header__nav-accordionmenu-item' %>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'header__nav-accordionmenu-item' %>
    </div>
  </div>
</div>

app/views/layouts/_meta.html.erb
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- vendor -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/exif-js/2.2.1/exif.min.js"></script>

</head>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render  "layouts/meta" %>
<body>
  <%= render  "layouts/header" %>
  <%= render  "shared/debug" if Rails.env.development? %>
  <div class="app-container">

    <main class="app__main-flex_container <%= "aside_#{content_for?(:aside_type) ? yield(:aside_type) : 'none'}" %>">
      <div id="flash_container">
        <%= render  "layouts/flash_messages" %>
      </div>
      <%= yield %>
    </main>

    <aside class="app__aside-<%= content_for?(:aside_type) ? yield(:aside_type) : 'none' %>">
      <ul class="app__aside-container">
        <%= render  "layouts/aside" %>
      </ul>
    </aside>
  </div>
  <%= render  "layouts/footer" %>
</body>
</html>